apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: hellospring
  namespace: default
spec:
  components:
    - name: hellospring
      type: webservice
      externalRevision: v6
      properties:
        image: docker.io/qiaolei81/hellospring
        port: 8080
        env:
          - name: spring.config.import
            value: optional:configserver:http://config-server:8888/
          - name: eureka.client.service-url.defaultZone
            value: http://eureka-server:8761/eureka
      traits:
        - type: ingress
          properties:
            domain: test.hellospring.com
            http:
              /: 8080